### ISSUE TITLE
Test task list

### ISSUE THREAD

**Issue by RickCogley** [eSolia/test1#8]
- [ ] @RickCogley a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [x] incomplete
- [x] completed
